### ISSUE TITLE
Adding Doc

### ISSUE THREAD

**Issue by dgdarlington** [flamencist/GenericConnectionViewer#3]
I tried pushing up a branch to add some doc to this, but I don't have access to push a branch. I like this Extension and what you're doing with it, just thinking adding an example would save people time.

### Example Pipeline Usage:

```
pool:
  vmImage: 'ubuntu-latest'

steps:
- task: GenericConnectionViewer@0
  inputs:
    credentials: '<My Generic Service Connection Name>'
    url: 'url'
    username: 'username'
    password: 'password'

- script: |
    echo "url=$(url)"
    echo "username=$(username)"
    echo "password=$(password)"
```
